name: Scan container for weaknesses
on:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: docker.io/giratot/languagetool:latest
        username: giratot
        password: ${{ secrets.REGISTRY_PASSWORD }}
