name: Test shell scripts

"on":
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  bats:
    name: Bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: .
      - name: Run actionlint
        uses: raven-actions/actionlint@v2
      - uses: bats-core/bats-action@4.0.0
        with:
          bats-version: 1.11.0
      - name: Run Bats tests
        run: bats tests
