name: Trivy Container Scan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * 3'

jobs:
  build:
    name: Trivy Container Scan & GitHub Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get LanguageTool Version
        run: |
            data=$(curl -s https://api.github.com/repos/languagetool-org/languagetool/tags)
            regex='\"name\": \"([0-9v.]{1,6})\"'

            if [[ $data =~ $regex ]]
            then
                echo "::set-output name=LT_VERSION::${BASH_REMATCH[1]:1}"
            fi
        shell: bash
        id: get-version

      - name: Print LT Version
        run: echo "LT Version is ${{ steps.get-version.outputs.LT_VERSION }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/giratot/languagetool:${{ steps.get-version.outputs.LT_VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: ${{ secrets.REGISTRY_USER }}
          TRIVY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
